Hanghae99-FinalProject-Buycation/FE-Buycation

src/App.js, src/index.js
폴더 구조 관련해서 에러 사항 고쳤습니다.
폴더 수정
close #3
=> ✨feat: 리액트 폴더 구조 생성 에러 사항 고치기

src/pages/Signup.jsx, src/shared/Router.js
주요 다섯 페이지에 대한 라우터 기본 설정 했습니다.
close  #10
=> ✨feat: 라우터 기본 설정

src/App.js, src/shared/GlobalStyles.js, src/styles/theme.js
emotion 사용해서 전역 스타일 적용해봤는데 직접 사용하면서 적용이 된건지 확인해 봐야 할 것 같습니다.
globalStyles에 전반적인 스타일 적용 / theme.js에 폰트사이즈 및 컬러 적용 후 app.js에서 ThemeProvider를 사용해 전역으로 사용할 수 있게 작업함
close #9
=> ✨feat : 전역 스타일 설정

package.json, src/App.js, src/shared/GlobalStyles.js, yarn.lock
=> ✨feat: 전역 스타일 설정 세팅

src/pages/Datails.jsx, src/pages/Main.jsx, src/shared/Router.js, src/shared/layout/Footer.jsx, src/shared/layout/Header.jsx, src/shared/layout/Layout.jsx
=> ✨feat : 라우터 설정

src/components/elements/ButtonBasic.jsx, src/components/elements/InputBasic.jsx
버튼과 인풋 컴포넌트 추가
버튼과 인풋 기본적인 뼈대 만들어보았습니다
close #18
=> ✨feat: 인풋, 버튼 최소단위 컴포넌트 작업

src/components/login/SignIn.jsx
=> ✨feat : 로그인 로직 기본 틀 구현

src/components/elements/ButtonBasic.jsx, src/components/elements/InputBasic.jsx, src/shared/GlobalStyles.js
버튼 컴포넌트 상세 로직을 설정했습니다.
- 디자인 시안에 따라 인풋, 버튼 컴포넌트의 defaultProps를 설정
- props, styles 관리
close #21
=> ✨feat: 버튼 컴포넌트 상세 로직 설정

src/index.js, src/styles/reset.css
reset.css 적용했습니다.
reset.css 파일 생성 후 index.js에서 import
close #15
=> ✨feat: reset.css 적용

src/components/elements/ButtonBasic.jsx
최소단위 버튼 수정
onClick 부분 onChange으로 오타난 거 수정!
close #23
=> ✨feat: 최소단위 버튼 수정

package.json, src/components/elements/InputBasic.jsx, src/components/login/SignIn.jsx, src/core/axios.js, src/core/instance.js, src/index.js, src/shared/Router.js, yarn.lock
=> ✨feat: 로그인 빈 값 예외처리

src/components/elements/InputBasic.jsx, src/components/login/SignIn.jsx
=> ✨feat: 변수명 수정

src/components/login/SignIn.jsx
로그인 서버 연동 전 로직 및 레이아웃 구현
- 로그인 서버 연동 전 로직 및 레이아웃 구현
close #7
=> ✨feat : 로그인 서버 연동 전 로직 및 레이아웃 구현

src/components/elements/InputCheckboxBasic.jsx
최소단위 컴포넌트(체크박스) 생성
- 기본 설정
close #30
=> ✨feat: 최소단위 컴포넌트(체크박스) 생성

src/components/signup/ConditionContent.js, src/components/signup/ConditionDiv.jsx, src/components/signup/FormContents.js, src/components/signup/SignupConditions.jsx, src/components/signup/SignupForm.jsx, src/pages/Signup.jsx, src/redux/modules/signupSlice.js
회원가입 서버 연동 전 로직 및 레이아웃 구현
- 스타일 작업
- 기본 핸들러 연결
close #12
=> ✨feat: 회원가입 서버 연동 전 로직 및 레이아웃 구현

src/components/login/SignIn.jsx, src/shared/Router.js, src/shared/layout/Header.jsx, src/shared/layout/Layout.jsx
레이아웃 / 헤더 틀 생성
- 레이아웃 / 헤더 틀 생성
close #28
=> ✨feat : 레이아웃 / 헤더 틀 생성

src/components/login/SignIn.jsx, src/index.js, src/redux/config/configStore.js, src/redux/modules/login/signinSlice.js, src/redux/modules/login/signupSlice.js
=> ✨feat: 로그인 API 연동

src/components/elements/ButtonBasic.jsx, src/components/elements/DialogBasic.jsx, src/components/elements/InputBasic.jsx
최소단위 컴포넌트 업데이트(ButtonBasic, InputBasic) 및 추가(DialogBasic)
- ButtonBasic에 gridArea 업데이트
- InputBasic에 gridArea 업데이트
- DialogBasic 추가
close #38
=> ✨feat: 최소단위 컴포넌트 업데이트(ButtonBasic, InputBasic) 및 추가(DialogBasic)

package.json, src/components/elements/ButtonBasic.jsx, src/components/elements/DialogBasic.jsx, src/components/elements/InputBasic.jsx, src/components/postcode/Postcode.jsx, yarn.lock
카카오 주소 API 컴포넌트 생성
- 카카오 주소 API 컴포넌트 생성
close #40
=> ✨feat: 카카오 주소 API 컴포넌트 생성

src/components/signup/SignupForm.jsx, src/redux/config/configStore.js, src/redux/modules/login/signupSlice.js
회원가입 POST dispatch 추가
회원가입 POST dispatch 추가
- extraReducer import, dispatch
- Slice signup 추가
- middleware 주석 처리
close #12
=> 🧪test: 회원가입 POST dispatch 추가

src/components/signup/SignupForm.jsx, src/redux/config/configStore.js, src/redux/modules/login/signupSlice.js, src/styles/theme.js
theme 요소 추가
- common.flexCenter 추가
- signup.gridDiv 추가
close #43
=> ✨feat: theme 요소 추가

src/components/login/SignIn.jsx, src/redux/config/configStore.js, src/redux/modules/login/signinSlice.js
로그인 API 통신 완료
- 로그인 API 통신 완료
close #36
=> ✨feat : 로그인 API 통신 완료

src/components/elements/ButtonBasic.jsx, src/components/elements/InputBasic.jsx, src/core/axios.js
공통 스타일 컴포넌트 수정
- 순서변경
- 주석정리
close #48
=> ✨feat : 공통 스타일 컴포넌트 수정

src/components/login/SignIn.jsx, src/components/login/outh/Oauth2RedirectHandler.jsx, src/core/env.js
=> ✨feat : 카카오 로그인 로직 구현

public/index.html, src/components/main/Map.jsx, src/components/main/PostingList.jsx, src/hooks/useMap.js, src/pages/MainPage.jsx
공통적으로 쓰이는 기본적인 Map 형태만 커스텀 Hooks로 만들었습니다.
close #52
=> ✨feat : 카카오 Map API 사용해서 지도 띄우기

package.json, src/components/elements/CardBasic.jsx, src/components/login/SignIn.jsx, src/components/main/Main.jsx, src/components/main/Map.jsx, src/components/main/PostingCard.jsx, src/components/main/PostingList.jsx, src/components/main/option.js, src/db/mainDB.json, src/index.css, src/pages/MainPage.jsx, src/shared/GlobalStyles.js, src/shared/layout/Layout.jsx, yarn.lock
메인페이지 레이아웃 구현
- 메이페이지 레이아웃 구현
close # 54
=> ✨feat : 메이페이지 레이아웃 구현

src/components/detail/Detail.jsx, src/pages/DatailsPage.jsx
상세페이지 레이아웃 작업했습니다.
- 상세페이지 레이아웃 작업
- 더미 데이터 연결
close #55
=> ✨feat: 상세페이지 레이아웃 작업

src/components/detail/Detail.jsx, src/db/detailDB.json
상세페이지 더미데이터 연결
-  상세페이지 더미데이터 연결 (detailDB.json)
close #58
=> ✨feat: 상세페이지 더미데이터 연결

package.json, src/components/elements/InputBasic.jsx, src/components/main/PostingList.jsx, src/components/main/option.js, src/components/posting/Posting.jsx, src/pages/PostingPage.jsx, src/shared/GlobalStyles.js, src/shared/Router.js, src/shared/layout/Layout.jsx, src/styles/theme.js
게시글 작성페이지 레이아웃
- 게시글 작성페이지 레이아웃
=> ✨게시글 작성페이지 레이아웃

src/components/posting/Posting.jsx
게시글 작성 페이지 레이아웃 구현
- 게시글 작성 페이지 레이아웃 구현
close #62
=> ✨feat : 게시글 작성 페이지 레이아웃 구현

src/shared/GlobalStyles.js
프리텐다드 웹폰트 추가
- GlobalStyles.js에 프리텐다드 글꼴 추가
close #67
=> ✨feat: 프리텐다드 웹폰트 추가

public/index.html, src/components/detail/Detail.jsx, src/db/detailDB.json, src/hooks/useTrademap.js
입력된 주소에 따라 지도 나오는 hook 추가
- 카카오 지도 API hook 추가 (useTrademap.js)
- index.html에 API 라이브러리 설정 추가
close #55
=> ✨feat: 입력된 주소에 따라 지도 나오는 hook 추가

src/components/main/option.js, src/components/posting/Posting.jsx, src/shared/GlobalStyles.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
close
=> feat : value 읽어오기

src/components/elements/ButtonBasic.jsx, src/components/elements/InputBasic.jsx, src/components/posting/Posting.jsx, src/utils/uploadImg.js
게시글 작성 페이지 API 연동 작업
- 게시글 작성 페이지 API 연동 작업
=> ✨feat : 게시글 작성 페이지 API 연동 작업

src/components/register/SignupConditions.jsx, src/components/register/SignupForm.jsx, src/redux/modules/login/signupSlice.js
회원가입 Slice 업데이트 및 주소 검색 모달 추가
- 회원가입 Slice 업데이트 및 주소 검색 모달 추가
close #12
=> ✨feat: 회원가입 Slice 업데이트 및 주소 검색 모달 추가

src/components/posting/Posting.jsx, src/components/register/SignupConditions.jsx, src/components/register/conditionContents.js, src/redux/modules/login/signinSlice.js, src/shared/GlobalStyles.js, src/styles/theme.js
글꼴 변경 작업, 컴포넌트 명 변경
- 글꼴 변경 작업, 컴포넌트 명 변경
=> ✨!hotfix : 에러 수정

src/components/posting/Posting.jsx, src/components/posting/perBudget.js, src/redux/modules/login/signinSlice.js, src/redux/modules/postingSlice.js, src/utils/option.js
게시글 작성 페이지 API 연동
- 게시글 작성 페이지 API 연동
- perBudget 소수점 버리는 걸로 로직 수정
close #79
=> ✨feat : 게시글 작성 페이지 API 연동

src/components/main/PostingList.jsx, src/redux/config/configStore.js, src/redux/modules/postingListSlice.js
메인 페이지 API 연동
- 메인 페이지 API 연동
- 리덕스 thunk 연동
- 내용을 적어주세요.
close #81
=> ✨feat : 메인 페이지 API 연동

src/components/elements/ButtonBasic.jsx
최소단위 버튼 타입 지정
- defaultProps에 type='button' 추가
- 기본 기능이 submit이던 버튼이 모두 button 타입으로 바뀌게 됨
close #84
=> 🐛fix: 최소단위 버튼 타입 지정

src/components/detail/Detail.jsx, src/redux/config/configStore.js, src/redux/modules/detailSlice.js
상세페이지 API 연결
- RTK 작업
- 데이터 연결
close #55
=> ✨feat: 상세페이지 API 연결

src/components/detail/Detail.jsx, src/hooks/useBuyLocation.js, src/redux/config/configStore.js, src/redux/modules/detailSlice.js, src/styles/theme.js
theme에 fontSize별 주석 및 lineHeight 속성 추가
- fontSize rem에 따른 px 규격 주석 추가
- 와이어 프레임 분석에 따른 lineHeignt 속성 추가
close #89
=> ✨feat: theme에 fontSize별 주석 및 lineHeight 속성 추가

src/components/detail/Detail.jsx, src/components/postcode/Postcode.jsx, src/hooks/useBuyLocation.js, src/redux/config/configStore.js, src/redux/modules/detailSlice.js, src/styles/theme.js
글 작성 페이지 모달 여닫는 리듀서 연결
- sendPostingModalStatus 추가
- sendPostingModalStatus 추가
close #40
=> ✨feat:글 작성 페이지 모달 여닫는 리듀서 연결

src/components/elements/CardBasic.jsx, src/components/main/PostingCard.jsx, src/components/posting/Posting.jsx
게시글 작성 페이지 빈값 예외처리
- 게시글 작성 페이지 빈값 예외처리
close #83
=> ✨feat : 게시글 작성 페이지 빈값 예외처리

src/components/detail/Detail.jsx
hook 주소 수정
- hook 주소 수정
close #55
=> 🐛hotfix: hook 주소 수정

src/components/main/PostingList.jsx, src/redux/modules/postingListSlice.js
메인 카테고리, 검색 기능
- 메인 카테고리, 검색 기능
=> ✨feat : 메인 카테고리, 검색 기능

src/components/main/PostingCard.jsx, src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/components/profile/MyProfile.jsx, src/components/profile/MyStar.jsx, src/components/profile/Profile.jsx, src/pages/ProfilePage.jsx, src/shared/Router.js
=> ✨feat : 프로필 페이지 레이아웃

src/styles/theme.js
theme에 메인 컬러 및 회색조 추가
- 메인 핑크 컬러 추가
- 주변부 회색조 추가 (grayList, grayWeak, grayStrong)
close #43
=> ✨design: theme에 메인 컬러 및 회색조 추가

package.json, public/index.html, src/components/main/Map.jsx, src/components/main/PostingCard.jsx, src/components/main/PostingList.jsx, src/core/env.js, src/db/mainDB.json, src/hooks/useMap.js, src/redux/modules/postingListSlice.js, yarn.lock
메인 지도 기능 업데이트
- 게시글 클릭 시, 해당 좌표로 중심 좌표 이동 처리
close #99
=> ✨feat : 메인 지도 기능 업데이트

src/components/login/SignIn.jsx, src/components/main/PostingList.jsx, src/components/posting/Posting.jsx, src/redux/modules/postingListSlice.js, src/utils/option.js
API 연동 전 메인페이지 검색 기능 로직구현했습니다.
- 검색 데이터
- 카테고리 데이터
- 정렬 데이터
=> ✨feat : 메인페이지 검색 기능 로직

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationList.jsx, src/components/detail/DetailCommentModal.jsx, src/components/detail/DetailMoreButton.jsx, src/components/detail/DetailPostingOptionModal.jsx, src/components/detail/DetailSpan.jsx, src/db/detailApplicationDB.json, src/db/detailDB.json, src/redux/modules/details/detailSlice.js
더보기 버튼 및 참가신청리스트 모달 추가
- 더보기 버튼 컴포넌트 추가
- 글수정, 삭제 모달 추가
- 참가신청리스트 모달 추가
- 댓글 수정 삭제 모달 추가
- detailSlice 위치 변경 (/details)
- 참가신청리스트 더미데이터 추가
- detailSlice 위치 바뀌었다고 오류 뜰 수 있습니다! /details/detailSlice로 변경해주시면 됩니다!
close #55
=> ✨feat: 더보기 버튼 및 참가신청리스트 모달 추가

src/components/elements/ButtonBasic.jsx, src/components/elements/InputBasic.jsx, src/components/login/SignIn.jsx, src/components/postcode/Postcode.jsx, src/components/posting/Posting.jsx, src/shared/GlobalStyles.js, src/shared/layout/Header.jsx, src/styles/theme.js
공통 스타일 컴포넌트 / Buttonbasic : 높이 3.188rem 통일, 색상 메인 컬러 적용
- 로그인 페이지 레이아웃, 공통 스타일 컴포넌트 수정
- 내용을 적어주세요.
close
=> ✨style : 로그인 페이지 레이아웃

src/components/register/SignupForm.jsx, src/components/register/signupContents.js
formContents -> signupContents 로 파일명 변경하였습니다.
- 파일명 변경 formContents -> signupContents
close #12
=> ✨rename: 파일명 변경 formContents -> signupContents

src/components/main/Map.jsx, src/components/profile/MyProfile.jsx, src/components/profile/Profile.jsx, src/db/profileDB.json
지도 렌더링 에러 처리
- 더미 데이터 -> 서버 데이터로 변경
- 빈 배열로 값이 들어와서 해당 값을 못 읽을 때 에러 처리
- 게시글 여러 마커 지도에 띄우기
close #126
=> ✨feat : 지도 렌더링 에러 처리

src/components/profile/MyProfile.jsx, src/components/profile/Profile.jsx, src/components/profile/modal/EditProfileModal.jsx, src/redux/config/configStore.js, src/redux/modules/profile/profileSlice.js
프로필 페이지 리덕스 연결
- 프로필 페이지 리덕스 연결
=> ✨프로필 페이지 리덕스 연결

src/components/main/PostingList.jsx, src/redux/modules/login/signinSlice.js
유저 아이디 로컬 스토리지 저장
- 유저 아이디 로컬 스토리지 저장
=> ✨ feat : 유저 아이디 로컬 스토리지 저장

src/components/main/PostingCard.jsx, src/shared/Router.js
메인-상세 라우터 세팅
- 라우터 페이지 및 메인 라우터 설정
close #137
=> ✨feat : 메인-상세 라우터 세팅

src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/redux/modules/profile/myListSlice.js, src/utils/editedData.js
데이터 형식 공통 함수 생성 / 모집 기한이 지났을 때 CSS 적용하고자 날짜 비교 데이터 생성했는데 doneStatus를 받고 있었네요,, 혹시나 일단 삭제 안하고 올리겠습니다.
- 주소 데이터 형식 변환
- 날짜 데이터 형식 변환
close #139
=> ✨feat : 데이터 형식 공통 함수 생성

src/components/posting/Posting.jsx
게시글 작성 페이지 레이아웃 수정
- 게시글 작성 페이지 레이아웃 수정
=> ✨feat : 게시글 작성 페이지 레이아웃 수정

src/components/login/SignIn.jsx, src/redux/modules/login/signinSlice.js
로그인 완료 시 메인 이동
- 리덕스 에서 statusCode 받아와서 작업
close #142
=> ✨feat : 로그인 완료 시 메인 이동

src/components/main/EmptyCard.jsx, src/components/main/PostingList.jsx, src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/components/profile/MyStar.jsx, src/components/profile/modal/ReviewModal.jsx, src/redux/config/configStore.js, src/redux/modules/profile/reviewsSlice.js
후기 작성 API 연동 전 로직 구현
- 레이아웃 수정
- 리뷰 조회 및 평점 남기기 리덕스 연동
close #144
=> ✨feat : 후기 작성 API 연동 전 로직 구현

src/components/detail/Detail.jsx, src/redux/modules/details/detailSlice.js
상세페이지 주소 연결 추가
- 상세페이지 주소 연결 추가 (param 값)
close #55
=> ✨feat: 상세페이지 주소 연결 추가

src/components/detail/Detail.jsx, src/components/modifyPosting/ModifyPosting.jsx, src/pages/DetailsPage.jsx, src/pages/ModifyPage.jsx, src/redux/modules/details/detailSlice.js, src/shared/Router.js
수정페이지 라우터 작업
- 수정페이지 라우터 연결 및 소소한 오타 수정
close #150
=> ✨feat: 수정페이지 라우터 작업

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationList.jsx, src/components/detail/DetailCommentForm.jsx, src/components/detail/DetailPostingOptionModal.jsx, src/redux/modules/details/detailSlice.js
참가신청 및 게시글 완료 기능 추가
- 참가신청 기능 추가
- 게시글 완료 기능 추가
close #55
=> ✨feat: 참가신청 및 게시글 완료 기능 추가

src/components/main/Map.jsx, src/components/profile/MyCreation.jsx, src/components/profile/MyStar.jsx, src/components/profile/modal/ReviewModal.jsx, src/redux/modules/profile/myListSlice.js, src/redux/modules/profile/reviewsSlice.js
리뷰 등록 및 남기기 API 연동 및 별점 예외처리
아직 별점 예외처리 작업이 조금 더 있긴한데 기능은 구현은 되서 먼저 올리겠습니다.
- 리뷰 등록 및 남기기 API 연동
- 별점 예외처리
=> ✨리뷰 등록 및 남기기 API 연동 및 별점 예외처리

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationList.jsx, src/redux/config/configStore.js, src/redux/modules/application/applicationSlice.js, src/redux/modules/details/detailSlice.js
상세페이지 내 참가 거절 수락 기능 활성화
- 참가 수락 POST 연결
- 참가 거절 DELETE 연결
- applicationSlice 분류
close #55
=> ✨feat: 참가 거절 수락 기능 활성화

src/components/modal/SmallModal.jsx, src/redux/config/configStore.js, src/redux/modules/modal/modalSlice.js, src/shared/layout/Header.jsx
헤더 마이페이지 모달 추가
- 상세페이지 모달 컴포넌트화 -> 헤더에 부착
- 모달 관리 리듀서 추가
close #156
=> ✨feat: 헤더 마이페이지 모달 추가

src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/redux/modules/modal/modalSlice.js, src/redux/modules/profile/reviewsSlice.js, src/shared/layout/Header.jsx
피그마에도 적어 놨는데 카트 클릭 시 해당 상세페이지로 가게 되면 모바일 화면에서는 실수가 잦을 것 같아서 우선은 이미지 클릭 시 이동하게끔 했습니다.!
- 이미지 클릭 시 해당 상세 페이지 이동
close #160
=> ✨이미지 클릭 시 해당 상세 페이지 이동

src/components/posting/Posting.jsx
posting min 조건 수정
- posting min 조건 수정
=> ✨!hoxfix : posting min 조건 수정

src/shared/GlobalStyles.js
a, button 태그에 cursor:pointer 추가
- a, button 태그에 cursor:pointer 추가
close #9
=> ✨feat: a, button에 cursor:pointer 추가

src/components/login/SignIn.jsx, src/components/login/outh/Oauth2RedirectHandler.jsx, src/pages/OauthPage.jsx, src/shared/Router.js
카카오 로그인 구현
- 카카오 로그인
close #50
=> ✨feat : 카카오 로그인 구현

src/components/headerModal/userModal.jsx, src/components/login/outh/Oauth2RedirectHandler.jsx, src/shared/layout/Header.jsx
나중에 헤더 아이콘에서 추가 모달이 계속 생길 것 같아서 폴더명이랑 파일명 수정해봤는데 괜찮으신가요? 참고로 헤더에 있는 모달을 shared 폴더에 넣을 지 commponent 폴더에 넣을 지 고민했었는데 연서 매니저님께서는 shared에 넣을 것 같다고 했는데 이거는 나중에 저희의 이유대로 다시 정해도 좋을 것 같아보여요!
토큰 예외처리 하면서 령빈님이 만들어 주신 모달 부분을 수정하게 되서 한번 확인 부탁드립니다 🙏
- 토큰이 있는 경우 : 마이페이지 / 로그아웃
- 토큰이 없는 경우 : 로그인
close #162
=> ✨feat : 헤더 아이콘 토큰 여부에 따른 예외 처리

src/components/headerModal/userModal.jsx, src/redux/modules/modal/modalSlice.js, src/shared/layout/Header.jsx
모달 바깥 영역 클릭 시 모달 해제
- 모달 내 hidden 속성 삭제
- Header에 modalStatus 유무에 따라 요소 보이도록 속성 추가
close #156
=> 🐛fix: 모달 바깥 영역 클릭 시 모달 해제

src/components/detail/Detail.jsx, src/components/detail/DetailCommentForm.jsx, src/components/detail/DetailPostingOptionModal.jsx, src/hooks/useBuyLocation.js, src/redux/modules/details/commentSlice.js, src/redux/modules/details/detailSlice.js
댓글 추가 기능, 글 삭제 기능 외 자잘한 수정과 리팩토링을 거쳤습니다. memberId를 어디서 선언할지 고민 중에 있습니다.
- 댓글 추가 기능
- 글 삭제 기능
- 미로그인 시 '참가 신청' 클릭 후 로그인하도록 유도
- 지도에 인포 윈도우 삭제 및 호버 알림말 교체
- 지도 마커 아이콘 변경
close #55
=> ✨feat: 댓글 추가 기능, 글 삭제 기능 외 자잘한 수정

src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/components/profile/MyProfile.jsx, src/components/profile/MyStar.jsx, src/components/profile/modal/EditProfileModal.jsx, src/redux/modules/profile/myListSlice.js, src/redux/modules/profile/profileSlice.js
마이페이지 렌더링 에러 처리
- 리덕스가 아닌 해당 컴포넌에서 로컬 스토리지에 저장된 데이터 읽어온 뒤 렌더링 하기
- 프로필 수정 시 성공 여부를 리덕스에 저장하고 해당 프로필이 보여지는 컴포넌트에서 가져와서 값 인식 후 렌더링 처리
close #170
=> ✨feat : 마이페이지 렌더링 에러 처리

src/components/detail/DetailCommentForm.jsx, src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/components/profile/MyProfile.jsx, src/components/profile/modal/EditProfileModal.jsx, src/redux/modules/profile/profileSlice.js
프로필 조회하는 부분에서 변수 명 명확히 하기 위해서 myProfile로 변경했는데 details 쪽에서도 사용하고 있더라구요! 그 부분도 변경한 네임으로 바꿨습니다!
- 마이페이지 API 설계 변경에 따른 로직 변경
close #179
=> ✨feat : 마이페이지 API 설계 변경에 따른 로직 변경

src/components/headerModal/userModal.jsx, src/core/axios.js, src/core/cookie.js, src/redux/modules/login/signinSlice.js, src/shared/layout/Header.jsx
로컬 스토리지 -> 쿠키로 토큰 저장
- 로컬 스토리지 -> 쿠키로 토큰 저장
close #176
=> ✨feat : 로컬 스토리지 - 쿠키로 토큰 저장

src/redux/modules/login/signinSlice.js
=> ✨!hotfix : 로그인 토큰

src/components/elements/InputBasic.jsx, src/components/modifyPosting/ModifyPosting.jsx, src/redux/modules/modifyPosting/modifyPostingSlice.js
수정 페이지 중간 작업(defaultValue 입력)까지 임시로 PR 보냅니다. 아직 defaultValue가 바로 state으로 들어오지 않는 문제가 있고, 어제 put 요청 시 에러났던 부분이 서버 미연결에 따른 사항인지 재확인이 필요해, PR 체크 이후 재확인할 예정입니다.
- InputBasic에 defaultValue 속성 추가
- modifyPostingSlice 추가
- InputBasic
close #150
=> ✨feat: 수정 페이지 중간 작업

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationList.jsx, src/components/detail/DetailMoreButton.jsx, src/components/detail/DetailPostingOptionModal.jsx, src/redux/modules/application/applicationSlice.js, src/redux/modules/details/detailSlice.js
토큰 저장 방식 변경에 따른 버튼 및 모달 분기 처리를 변경했습니다.
- memberId -> details.myPosting 변경
- 상세페이지 GET 요청 시 연결 axios instance를 baseURLwToken으로 변경
close #55
=> ✨feat: 토큰 저장 방식 변경에 따른 분기 처리 변경

src/components/register/SignupPiece.jsx, src/redux/modules/login/signupSlice.js
이메일 인증 방식을 변경했습니다. get 요청 이후 프론트단에서 비교하던 로직을 백엔드 단의 put 요청을 통해 인증번호를 비교하는 방식으로 변경했습니다.
- signupSlice에 __emailValidationCheck PUT 요청 추가
- signupSlice
close #12
=> ✨feat: 이메일 인증 방식 변경

src/components/login/SignIn.jsx, src/redux/modules/login/signinSlice.js
로그인 완료 후 상태값 초기화
- 로그인 완료 후 상태값 초기화
close #142
=> ✨로그인 완료 후 상태값 초기화

src/components/posting/Posting.jsx, src/redux/modules/posting/postingSlice.js, src/redux/modules/profile/profileSlice.js
작성페이지 라우터 예외처리
- 작성페이지 라우터 예외처리
=> ✨feat : 작성페이지 라우터 예외처리

src/components/modifyPosting/ModifyPosting.jsx, src/redux/modules/modifyPosting/modifyPostingSlice.js
게시글 수정 기능을 추가했습니다. 카테고리와 사진의 defaultValue 설정을 제외한 나머지 부분입니다.
- 게시글 수정 기능 추가
close #150
=> ✨feat: 게시글 수정기능 추가

src/components/detail/Detail.jsx, src/hooks/useBuyLocation.js
상세페이지 거래 장소 지도에 로딩 후 즉시 표시
- 거래 장소 지도에 로딩 후 즉시 표시
close #55
=> ✨feat: 거래 장소 지도에 로딩 후 즉시 표시

src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/components/profile/Profile.jsx, src/components/profile/ProfileInfo.jsx, src/components/profile/ProfileStar.jsx, src/components/profile/modal/EditProfileModal.jsx, src/components/profile/modal/ReviewModal.jsx, src/redux/modules/profile/profileSlice.js
마이프로필 페이지 파일 재구조
- 마이프로필 페이지 파일 재구조
=> ✨마이프로필 페이지 파일 재구조

src/components/profile/modal/ReviewModal.jsx
평점 남기기 목록 조회 시 상태에 따른 버튼 처리
- 평점 남기기 목록 조회 시 상태에 따른 버튼 처리
close #193
=> ✨feat : 평점 남기기 목록 조회 시 상태에 따른 버튼 처리

src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/components/profile/MyProfile.jsx, src/components/profile/ProfileInfo.jsx, src/components/profile/ProfileStar.jsx, src/components/profile/modal/EditProfileModal.jsx, src/components/profile/modal/ReviewModal.jsx, src/pages/MyProfilePage.jsx, src/redux/modules/profile/profileSlice.js, src/shared/Router.js, src/shared/layout/Header.jsx
다른 유저의 프로필 컴포넌트 분기 처리
- 다른 유저의 프로필 컴포넌트 분기 처리
close #196
=> ✨feat : 다른 유저의 프로필 컴포넌트 분기 처리

src/components/detail/Detail.jsx, src/components/detail/DetailCommentForm.jsx, src/components/modifyPosting/ModifyPosting.jsx, src/components/postcode/Postcode.jsx, src/components/register/SignupConditions.jsx, src/components/register/SignupForm.jsx, src/components/register/SignupPieceMobile.jsx, src/components/register/signupContents.js
카카오 주소 API 너비 변경 처리 및 모달 숨김 로직을 변경해 적용하였습니다.
- Postcode 수정
- Postcode 컴포넌트 hidden 속성 삭제
- postcodeModalStatus (useSelector)와 함께 사용해 부모 컴포넌트 단에서 숨김 분기 처리하도록 변경
- Postcode에 props로 width를 넘길 경우 적용되도록 적용 (너비 지정 없을 경우 기본 370px)
close #201
=> ✨feat: 카카오 주소 API 너비 변경 처리 및 모달 숨김 로직 변경

src/components/detail/Detail.jsx, src/components/detail/DetailCommentForm.jsx, src/components/register/SignupConditions.jsx, src/components/register/SignupForm.jsx, src/components/register/SignupPieceMobile.jsx, src/components/register/signupContents.js
상세 페이지, 회원가입 페이지 레이아웃을 수정하고 모바일뷰에 대응했습니다.
- 상세 페이지 레이아웃
- 회원가입 레이아웃
- 회원가입 닉네임 유효성 검증 추가
close #114
=> ✨feat: 페이지 레이아웃 수정 및 모바일뷰 대응

src/components/register/SignupForm.jsx, src/components/register/SignupPiece.jsx, src/components/register/SignupPieceMobile.jsx
비밀번호 공백 검사 추가
- 비밀번호 공백 검사 추가
close #12
=> 🐛fix: 비밀번호 공백 검사

src/components/headerModal/userModal.jsx, src/core/cookie.js, src/shared/layout/Header.jsx
로그 아웃 시 쿠키 토큰 값 삭제
- 로그 아웃 시 쿠키 토큰 값 삭제
close #204
=> ✨feat : 로그 아웃 시 쿠키 토큰 값 삭제

src/components/register/SignupPiece.jsx, src/components/register/SignupPieceMobile.jsx
닉네임 유효성 미완
- 닉네임 유효성 미완
close #12
=> 🐛fix: 닉네임 유효성 미완

src/components/register/SignupForm.jsx
이메일 인증번호 프론트단 검증 제외
- 이메일 인증번호 프론트단 검증 제외
- getEmailValidation 해제
close #12
=> 🐛fix: 이메일 인증번호 프론트단 검증 제외

src/components/main/PostingCard.jsx, src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/utils/editedData.js
제목 15글자만 보이게 데이터 수정
- 제목 15글자만 보이게 데이터 수정
close #210
=> ✨feat : 제목 15글자만 보이게 데이터 수정

src/components/detail/Detail.jsx, src/shared/layout/Header.jsx
패딩 및 아이콘 커서 수정
- 패딩 및 아이콘 커서 수정
close #114
=> 🐛design: 패딩 및 아이콘 커서 수정

src/components/detail/DetailApplicationList.jsx, src/components/detail/elements/DetailSpan.jsx, src/redux/modules/application/applicationSlice.js, src/redux/modules/login/signupSlice.js
신청자 리스트 높이 미조정 외
- 신청자 리스트 높이 미조정 외
close #114
=> ♻️design: 신청자 리스트 높이 미조정 외

src/utils/editedData.js
제목 데이터 수정
- 제목 데이터 수정 : 11글자 이상이면 ... 처리
close #210
=> ✨feat : 제목 데이터 수정

src/components/header/UserModal.jsx, src/shared/layout/Footer.jsx, src/shared/layout/Header.jsx
나중에 헤더 부분에 채팅 및 알림 기능 등등이 추가 될 것 같아 폴더명 이름 바꿔봤습니다! 확인 후 의견 남겨주세요 :)
- 헤더 관련 폴더 구조 재정리
=> ✨feat : 헤더 관련 폴더 구조 재정리

src/components/detail/Detail.jsx, src/components/profile/Profile.jsx, src/redux/modules/profile/profileSlice.js, src/shared/Router.js
상세에서 프로필 넘어갈 수 있도록 details 컴포넌트 수정했습니다. 다른데에 영향이 없는지 확인 부탁드려요 ㅠㅠ
- 프로필 기능 구현
close #218
=> ✨feat : 프로필 기능 구현

src/components/profile/modal/ReviewModal.jsx, src/redux/modules/profile/reviewsSlice.js
후기 등록 시 바로 완료 css 적용
-후기 등록 시 바로 완료 css 적용
close #222
=> ✨feat : 후기 등록 시 바로 완료 css 적용

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationBody.jsx, src/redux/modules/application/applicationSlice.js, src/utils/editedData.js
상세페이지 자잘한 css 수정 외
- 참가자 10명 이상일 경우 상세페이지 아이콘 하나만 보이게 작업
- 참가 신청 post 요청에 필요 없는 데이터 삭제
- 공구 금액 자릿수 계산 함수 생성 및 연결
- 태블릿뷰 가로 768px 대응 이미지 높이 변경 처리
close #55
=> ♻️refactor: 상세페이지 자잘한 css 수정 외

src/components/detail/Detail.jsx, src/shared/GlobalStyles.js
로컬 폰트로 웹폰트 교체 및 볼드 굵기 600으로 통일
- 프리텐다드 레귤러, 세미볼드, 볼드 연결 추가
- 상세페이지 내 볼드 굵기 700->600
close #225
=> ♻️refactor: 로컬 폰트로 웹폰트 교체 및 볼드 굵기 600으로 통일

package.json, src/components/detail/Detail.jsx, src/components/detail/modals/DetailCommentModal.jsx, src/components/header/UserModal.jsx, src/components/login/SignIn.jsx, src/components/login/outh/Oauth2RedirectHandler.jsx, src/components/modifyPosting/ModifyPosting.jsx, src/components/posting/Posting.jsx, src/components/posting/perBudget.js, src/components/profile/modal/EditProfileModal.jsx, src/components/profile/modal/ReviewModal.jsx, src/redux/modules/login/signinSlice.js, src/redux/modules/posting/postingSlice.js, src/redux/modules/profile/profileSlice.js, src/shared/layout/Header.jsx, src/shared/layout/Layout.jsx, src/utils/uploadImg.js, yarn.lock
console.log 주석처리
- console.log 주석처리
close #216
=> ✨feat : console.log 주석처리

src/components/main/PostingCard.jsx
가격 수정 데이터 사용
- 가격 수정 데이터 사용
close #229
=> ✨feat : 가격 수정 데이터 사용

public/index.html, src/components/login/SignIn.jsx, src/components/main/PostingList.jsx
input 확대 제거
keyword enter 이벤트 적용
-  input 확대 제거
-  keyword enter 이벤트 적용
close #231
=> ✨feat : 모바일 이용 시 자동 효과 없애기

package.json, src/components/login/SignIn.jsx, src/redux/modules/login/signinSlice.js, yarn.lock
=> ✨feat : sweetAlert 적용

src/components/header/UserModal.jsx, src/components/main/Main.jsx, src/shared/layout/Header.jsx
헤더 반응형에 따라 UI 수정했습니다. 변경된 부분 확인 부탁드려요!
1. 한가지 어려웠던 부분이 헤더 로고가 삼색 줄 아이콘일 때는 괜찮은데 로그인 버튼일 때 길어지면서 로고가 가운데에서 왼쪽옆으로 이동하더라구요! 같이 로그인 버튼 부분 길이 고민해 주시면 좋을 것 같아요!
기타사항
=> feat : 헤더 반응형에 따라 UI 수정

src/components/login/SignIn.jsx, src/components/posting/Posting.jsx, src/components/profile/modal/EditProfileModal.jsx, src/redux/modules/posting/postingSlice.js, src/redux/modules/profile/profileSlice.js, src/redux/modules/profile/reviewsSlice.js
sweetAlert2 라이브러리 적용한 커스텀 alert 띄우기
- sweetAlert2 라이브러리 적용한 커스텀 alert 띄우기
- 1.로그인 alert
- 2.게시글 작성 alert
- 3.프로필 수정 alert
close #233
=> ✨feat : sweetAlert2 라이브러리 적용

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationBody.jsx, src/components/detail/DetailApplicationList.jsx, src/components/detail/DetailCommentForm.jsx, src/redux/config/configStore.js, src/redux/modules/details/commentSlice.js
상세페이지 댓글 즉시 렌더 및 참가자리스트 링크 작업
- 댓글 등록 렌더
- 참가자리스트 클릭 시 프로필 연결
- 참가자 사진 없을 시 기본 사진 출력
- 기본 볼드 폰트 크기 변경 700->600
close #55
=> ✨상세페이지 댓글 및 참가자리스트 작업

src/components/header/Alarm.jsx, src/components/main/Main.jsx, src/components/main/PostingList.jsx, src/shared/layout/Header.jsx
헤더 컴포넌트가 조건 처리때문에 코드가 지저분한 것 같아요 ,, 나중에 리팩토리 때 같이 고민해주세요 ㅠ.ㅠ
- 알림 UI 구현
=> ✨feat : 알림 UI 구현

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationBtns.jsx, src/components/detail/DetailApplicationList.jsx, src/components/detail/DetailCommentList.jsx, src/components/detail/DetailContent.jsx, src/components/detail/DetailCreatorProfile.jsx, src/components/detail/elements/DetailSpan.jsx, src/redux/modules/application/applicationSlice.js
참가 취소 버튼 분기 추가 및 컴포넌트 분리
- 참가 취소 버튼 분기 추가
- 상세페이지 컴포넌트 분리
close #55
=> ✨feat: 참가 취소 버튼 분기 추가 및 컴포넌트 분리

src/shared/layout/Header.jsx
헤더 탭바 아이콘 수정
- 헤더 탭바 아이콘 수정
close #235
=> ✨feat : 헤더 탭바 아이콘 수정

src/components/header/Alarm.jsx
=> ✨feat : 알림 내용 UI 수정

src/components/modifyPosting/ModifyPosting.jsx
카테고리 defaultValue 및 에러 수정
- 카테고리 defaultValue 및 에러 수정
close #150
=> 🐛fix: 카테고리 defaultValue 및 에러 수정

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationBtns.jsx, src/components/modifyPosting/ModifyPosting.jsx, src/redux/modules/application/applicationSlice.js
참가 취소 버튼 분기 로직 수정
- 참가자 자신이 참가되었는지를 알 수 있는 API 항목 추가에 따른 참가 취소 버튼 분기 로직 수정
close #55
=> ♻️refactor: 참가 취소 버튼 분기 로직 수정

src/components/header/Alarm.jsx, src/redux/modules/alarm/alarmSlice.js
알림 삭제 API 로직 구현
- 알림 삭제 API 로직 구현
=> ✨feat : 알림 삭제 API 로직 구현

src/components/header/Alarm.jsx, src/redux/modules/alarm/alarmSlice.js
알림 읽음 표시 기능 구현
- 알림 읽음 표시 기능 구현
- patch를 통한 boolean값 변경
=> ✨feat: 알림 읽음 표시 기능 구현

src/components/header/Alarm.jsx, src/redux/modules/alarm/alarmSlice.js, src/shared/layout/Header.jsx
알람 개수에 따른 아이콘 색상 변화
- 알람 개수에 따른 아이콘 색상 변화
=> ✨feat : 알람 개수에 따른 아이콘 색상 변화

src/components/header/Alarm.jsx, src/utils/editedData.js
알림 제목 데이터 길이 20 수정
- 알림 제목 데이터 길이 20 수정
=> ✨feat : 알림 제목 데이터 길이 20 수정

src/components/posting/Posting.jsx, src/redux/modules/profile/profileSlice.js
커스텀 alert 적용
- posting 빈값 alert -> 커스텀 alert 적용
=> ✨feat : 커스텀 alert 적용

src/components/chat/Chatroom.jsx, src/components/chat/ChatroomMod.jsx, src/components/chat/ChatroomModMod.jsx, src/redux/modules/chat/chatSlice.js, src/shared/Router.js
채팅 기능 PC 레이아웃 구현 및 라우터 연결 진행하였습니다. 본 파일 이외에도 테스트를 위한 파일 두 개(ChatroomMod.jsx, ChatroomModMod.jsx)를 라우터에 추가하였고 테스트가 완료되면 삭제할 예정입니다. env 파일에 변경은 없습니다.
- 채팅 PC 레이아웃 구현
- 라우터 연결
- 테스트 파일 라우터 연결
- 관련 패키지 설치
- 소켓 관련 패키지 5개를 추가하였습니다 (FE 문서에 기재)
close #259
=> ✨feat: 채팅 PC 레이아웃 구현 및 라우터 연결

src/components/chat/Chatroom.jsx, src/redux/config/configStore.js
채팅 모바일 레이아웃 구현
- 채팅 모바일 레이아웃 구현
close #259
=> ✨feat: 채팅 모바일 레이아웃 구현

src/components/chat/Chatroom.jsx, src/components/header/HeaderPc.jsx, src/components/header/UserModal.jsx, src/redux/modules/modal/modalSlice.js, src/shared/layout/Header.jsx
헤더에 채팅 추가 및 모달 연결
- 헤더 메뉴에 채팅 버튼 추가
- 채팅 모달 연결
close #259
=> ✨feat: 헤더에 채팅 추가 및 모달 연결

src/components/chat/Chatroom.jsx, src/hooks/useOutsideClick.js
모달 바깥 클릭 시 모달 닫히게 처리
- 모달 바깥 클릭 시 모달 닫히게 처리
- 모달보다 vh 작을 때 모달 height 튀어나오는 현상 해결
close #259
=> ✨feat: 모달 바깥 클릭 시 모달 닫히게 처리

src/components/chat/Chatroom.jsx
대기실(채팅 기능 열자마자 보이는 상태)에서 채팅방 정보 가림 처리
- 대기실에서 채팅방 정보 가림 처리
close #259
=> ✨feat: 대기실에서 채팅방 정보 가림 처리

src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/shared/layout/Header.jsx
프로필 페이지 완료 게시글 이미지 조정
- 프로필 페이지 완료 게시글 이미지 조정
close #269
=> ✨feat : 프로필 페이지 완료 게시글 이미지 조정

package.json
=> ✨feat : 깃 액션 자동 배포화

src/components/detail/Detail.jsx, src/components/detail/DetailCommentList.jsx, src/components/detail/modals/DetailCommentModal.jsx, src/redux/modules/details/commentSlice.js
댓글 삭제 기능을 구현했습니다. 렌더링 시 새로고침이 되는 현상은 차후 수정하겠습니다.
- 댓글 모달 하나씩 띄우기
- 댓글 삭제
close #271
=> ✨feat: 댓글 삭제 기능 구현

.github/workflows/deploy.yml
깃액션 자동 배포
- Env 환경 변수 설정 추가
close #273
=> ✨feat : 깃액션 자동 배포

src/redux/modules/alarm/alarmSlice.js, src/shared/layout/Header.jsx
=> ✨feat : SSE 알림 기능 구현

src/components/chat/ChatZone.jsx, src/components/chat/Chatroom.jsx, src/components/chat/ChatroomMod.jsx, src/components/chat/ChatroomModMod.jsx, src/redux/modules/chat/chatSlice.js
내 메시지 말풍선 디자인 외 테스트 중입니다.
- 내 메시지 말풍선 디자인 입힘
close #259
=> ✨design: 내 메시지 디자인 설정

src/components/detail/Detail.jsx, src/components/detail/DetailCommentList.jsx, src/components/detail/modals/DetailCommentModal.jsx, src/redux/modules/details/commentSlice.js
댓글 삭제 기능
- 댓글 삭제 기능
close #271
=> ✨feat: 댓글 삭제 기능

src/components/elements/InputBasic.jsx, src/components/login/SignIn.jsx, src/components/posting/Posting.jsx
defaultValue 제거
- defaultValue 제거
close #278
=> ✨feat : defaultValue 제거

src/components/header/Alarm.jsx, src/components/main/PostingList.jsx, src/components/profile/MyParicipation.jsx, src/styles/theme.js
=> ✨feat : 알림 호버 CSS 적용

src/components/header/HeaderMobile.jsx, src/components/header/HeaderPc.jsx, src/components/header/guideModal/GuideModal.jsx, src/components/profile/modal/EditProfileModal.jsx, src/shared/layout/Header.jsx
유저 가이드 모달 UI 구현
이미지까지 테스트로 넣어볼려고 했는데 이미지 전체 다운로드 방법을 몰라 실패했습니다...😭
- 유저 가이드 모달 UI 구현
=> ✨유저 가이드 모달 UI 구현

src/components/profile/modal/EditProfileModal.jsx, src/redux/modules/profile/myListSlice.js, src/shared/layout/Header.jsx
=> ✨feat: 주석 및 콘솔 정리

src/components/header/Alarm.jsx, src/components/header/HeaderMobile.jsx, src/components/header/HeaderPc.jsx, src/components/login/outh/Oauth2RedirectHandler.jsx, src/shared/layout/Header.jsx
=> ✨feat : 알림 UI 수정

src/components/detail/DetailCommentForm.jsx, src/components/detail/DetailCommentList.jsx, src/components/detail/modals/DetailCommentModal.jsx, src/redux/modules/details/commentSlice.js
댓글 수정 기능을 추가하였습니다.
- 댓글 수정 기능 추가
close #271
=> ✨feat: 댓글 수정 기능

src/components/detail/DetailCommentForm.jsx, src/components/detail/DetailCommentList.jsx, src/components/detail/modals/DetailCommentModal.jsx
주석 정리, 쓰지 않는 변수 정리
- 주석 정리, 쓰지 않는 변수 정리
close #271
=> ♻️refactor: 주석 정리, 쓰지 않는 변수 정리

src/components/detail/Detail.jsx, src/components/modifyPosting/ModifyPosting.jsx, src/redux/modules/modifyPosting/modifyPostingSlice.js
이미지 미 수정 시 기존 데이터 사용하도록 처리하였습니다. 또한 주소 미선택 시 변경되지 않던 점 수정했습니다.
- 이미지 미 수정 시 기존 이미지 연결
- 기존 주소 연결
close #150
=> ✨feat: 이미지 데이터 및 주소 연결

src/components/register/SignupForm.jsx, src/redux/modules/details/commentSlice.js
주석 제거
- SignupForm, commentSlice 내 주석 제거
close #173
=> 📝docs: 주석 제거

src/components/register/SignupPiece.jsx
sweetAlert2 적용
- sweetAlert2 적용
close #12
=> ✨feat: sweetAlert2 적용

src/components/detail/DetailCommentList.jsx
댓글창 사라진 문제 수정
- 댓글창에 className = 'show' 지정
close #271
=> 🐛fix: 댓글창 사라진 문제 수정

src/components/detail/DetailApplicationBtns.jsx, src/components/detail/DetailApplicationList.jsx, src/redux/modules/application/applicationSlice.js
참가 수락/거절 버튼 클릭 시 리스트에서 즉시 사라지게 처리하였습니다.
- 참가 수락/거절 즉시 렌더
close #55
=> ✨feat: 참가 수락/거절 즉시 렌더

src/components/header/Alarm.jsx, src/components/header/HeaderPc.jsx, src/components/profile/MyProfile.jsx, src/components/profile/Profile.jsx
아이콘 이미지 사이즈 조정
- 아이콘 이미지 사이즈 조정 높이 25px 로 동일시 함
=> ✨feat : 아이콘 이미지 사이즈 조정

src/components/detail/DetailCommentList.jsx, src/components/detail/DetailContent.jsx
댓글 및 상세페이지 본문의 줄바꿈 처리를 진행했습니다.
- p태그 안에 white-space: pre-wrap 추가
close #114
=> 🐛fix: 줄바꿈 처리

src/components/elements/InputBasic.jsx, src/components/posting/Posting.jsx, src/index.css, src/shared/GlobalStyles.js
모바일 css 수정
- 모바일 웹일때 a 태그 기본 파란색상으로 나오는 거 수정
- Input 창 높이 줄어드는거 수정
=> ✨feat :  모바일 css 수정

src/components/login/SignIn.jsx, src/components/posting/Posting.jsx, src/components/profile/modal/EditProfileModal.jsx, src/index.css, src/shared/GlobalStyles.js
=> ✨feat : 모바일 반응형 수정

src/components/detail/DetailCommentForm.jsx
댓글 추가 기능 누락 수정
- 댓글 추가 기능 누락 수정
close #271
=> 🐛 fix: 댓글 추가 기능 누락 수정

src/components/chat/ChatZone.jsx, src/components/chat/Chatroom.jsx
=> 🐛fix: 연결문제 해결

src/shared/GlobalStyles.js
IOS인 경우 기존에 적용된 CSS 제거
- IOS인 경우 기존에 적용된 CSS 제거
=> ✨feat : IOS인 경우 기존에 적용된 CSS 제거

.github/workflows/deploy.yml, src/components/header/UserModal.jsx, src/components/profile/MyProfile.jsx, src/components/profile/Profile.jsx
IOS 반응형 수정 및 env 추가
- IOS 반응형 수정 및 env 추가
=> ✨feat : IOS 반응형 수정 및 env 추가

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationBtns.jsx, src/components/detail/DetailCommentForm.jsx, src/components/detail/DetailContent.jsx
403 getMyProfile 에러 처리
- 403 getMyProfile 에러 처리
close #55
=> 🐛fix: 403 getMyProfile 에러 처리

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationBtns.jsx, src/components/detail/DetailApplicationList.jsx, src/components/detail/DetailCommentForm.jsx, src/components/detail/modals/DetailPostingOptionModal.jsx
500 members/NaN 에러를 처리하였습니다. 또한 게시글 완료 시 마이페이지로 이동하도록 처리하였습니다.
- bugfix
- 완료 시 마이페이지 이동 처리
close #55
=> 🐛fix: 500 members/NaN 에러 처리 외

src/components/header/guideModal/GuideModal.jsx
=> ✨feat : 유저 가이드 스피너 추가

src/components/header/guideModal/GuideModal.jsx
령빈님 저희 이미지 파일 용량이 커서 혹시나 로컬에 저장하면 성능적 측면이나 로딩에 문제가 있을 까 싶어서 이미지 파일을 저희 s3 업로드하고 URL을 가져오는 방식으로 바꿨습니다! 로딩 부분은 방금 올린 머지에 있고 현재는 로딩부분을 제외하고 올리겠습니다!
- 이미지 파일 s3 업로드
=> ✨feat : 이미지 파일 s3 업로드

src/components/header/guideModal/GuideModal.jsx, src/components/login/SignIn.jsx, src/components/profile/modal/EditProfileModal.jsx, src/styles/theme.js
모바일(IOS) 반응형 수정
- 모바일(IOS) 반응형 수정
=> ✨feat : 모바일(IOS) 반응형 수정

src/components/detail/DetailCommentList.jsx
댓글 수정삭제 모달 로직 변경
- 댓글 수정삭제 모달 로직 변경 (status 값 추가)
close #271
=> 🐛fix: 댓글 수정삭제 모달 로직 변경

src/shared/GlobalStyles.js
모바일(IOS) 이미지 반응형 수정
- 모바일(IOS) 이미지 반응형 수정
=> ✨feat : 모바일(IOS) 이미지 반응형 수정

src/core/axios.js, src/core/env.js, src/shared/layout/Header.jsx
=> ✨feat : 알림 SEE 테스터 서버

src/core/axios.js, src/core/env.js, src/shared/layout/Header.jsx
=> ✨feat : SSE 테스트

src/assets/headerIcon/modalClose.svg, src/components/header/HeaderMobile.jsx, src/components/header/HeaderPc.jsx, src/components/header/guideModal/GuideModal.jsx, src/components/main/PostingCard.jsx, src/components/profile/modal/EditProfileModal.jsx
아이콘 수정 및 사이즈 조절
- 아이콘 수정 및 사이즈 조절
=> ✨feat : 아이콘 수정 및 사이즈 조절

src/components/header/guideModal/GuideModal.jsx, src/components/login/SignIn.jsx, src/components/main/EmptyCard.jsx, src/components/main/Main.jsx, src/components/main/PostingCard.jsx, src/components/profile/modal/EditProfileModal.jsx, src/shared/GlobalStyles.js
버튼 크기 조정 및 문구 수정
- 버튼 크기 조정 및 문구 수정
=> ✨feat : 버튼 크기 조정 및 문구 수정

src/components/header/guideModal/GuideModal.jsx
=> ✨feat : 가이드 이미지 용량 조정

src/components/header/guideModal/GuideModal.jsx
=> ✨feat : 사파리 이미지 흐림 수정

src/components/header/guideModal/GuideModal.jsx
=> ✨feat : 가로 스크롤 제거

src/components/chat/ChatZone.jsx, src/components/chat/Chatroom.jsx, src/shared/layout/Header.jsx
STOMP 설정을 통한 https 연결
- https 연결
close #259
=> ✨feat: https 연결

src/components/chat/Chatroom.jsx
=> 📝docs: 주석 삭제

src/components/posting/Posting.jsx, src/components/profile/modal/EditProfileModal.jsx, src/shared/layout/Header.jsx
=> ✨feat : input 높이 수정

src/components/header/HeaderMobile.jsx, src/components/header/HeaderPc.jsx, src/components/header/UserModal.jsx
=> ✨feat : 헤더 아이콘 호버 적용

src/components/header/HeaderMobile.jsx, src/components/header/HeaderPc.jsx
=> ✨feat : 알림 UI 조건문 수정

src/components/chat/ChatZone.jsx, src/components/chat/Chatroom.jsx, src/redux/modules/chat/chatSlice.js
중복 구독 취소 처리
- 중복 구독 취소 처리
close #259
=> ✨feat: 중복 구독 취소 처리

src/components/chat/ChatZone.jsx, src/components/chat/Chatroom.jsx
즉시 렌더 외 버그 수정
- dispatch -> then 사용하여 비동기 처리
close #259
=> ✨feat: 즉시 렌더 외 버그 수정

src/components/header/HeaderMobile.jsx, src/components/header/HeaderPc.jsx, src/core/axios.js
데이터 응답 시 에러 처리
- 데이터 응답 시 에러 처리
=> ✨feat : 데이터 응답 시 에러 처리

src/components/posting/Posting.jsx, src/components/profile/modal/EditProfileModal.jsx
테스트 배포 전 기능 수정
- 게시글 작성 모바일인 경우 스크롤 헤더 제외
- 프로필 수정버튼 누르면 모달 닫기
=> ✨feat : 테스트 배포 전 기능 수정

src/redux/config/configStore.js
=> ✨feat : devtools 비활성화

src/components/detail/Detail.jsx, src/components/detail/DetailCommentForm.jsx, src/components/detail/modals/DetailCommentModal.jsx, src/components/modifyPosting/ModifyPosting.jsx, src/components/register/SignupConditions.jsx, src/components/register/SignupPiece.jsx, src/components/register/conditionContents.js
전반적인 버그 처리
- 전반적인 버그 처리
close #345
=> 🐛fix: 전반적인 버그 처리

src/components/chat/ChatZone.jsx, src/components/chat/Chatroom.jsx, src/components/modifyPosting/ModifyPosting.jsx
좌표값 누락으로 지도 불러오지 못하던 문제 해결
- 좌표값 누락으로 지도 불러오지 못하던 문제 해결
close
=> 🐛fix: 좌표값 누락으로 지도 불러오지 못하던 문제 해결

src/shared/layout/Header.jsx
=> ✨테스트 배포 최종

src/components/profile/modal/ReviewModal.jsx
후기 남기기 높이 지정 및 스크롤 생성
- 후기 남기기 높이 지정 및 스크롤 생성
=> ✨feat : 후기 남기기 높이 지정 및 스크롤 생성

src/components/posting/Posting.jsx
게시글 작성 내용 글자 수 세기 기능 추가
- 게시글 작성 내용 글자 수 세기 기능 추가
=> ✨feat : 게시글 작성 내용 글자 수 세기 기능 추가

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationBody.jsx, src/components/detail/DetailCommentList.jsx, src/components/detail/DetailCommentModifyForm.jsx, src/components/detail/DetailCreatorProfile.jsx, src/components/detail/modals/DetailCommentModal.jsx, src/components/modifyPosting/ModifyPosting.jsx, src/components/register/SignupForm.jsx, src/redux/modules/details/commentSlice.js, src/redux/modules/login/signupSlice.js
상세페이지, 회원가입 버그 수정
- 상세페이지, 회원가입 버그 수정
close
=> 🐛fix: 상세페이지, 회원가입 버그 수정

src/components/posting/Posting.jsx
게시글 작성 addressDetail 개선
- 게시글 작성 addressDetail 에러 수정
=> ✨feat : 게시글 작성 addressDetail 개선

src/components/detail/Detail.jsx
존재하지 않는 상세페이지 진입 시 메인으로 이동 처리
- 존재하지 않는 상세페이지 진입 시 메인으로 이동 처리
close
=> 🐛fix: 존재하지 않는 상세페이지 진입 시 메인으로 이동 처리

src/components/posting/Posting.jsx, src/components/posting/perBudget.js
유저 피드백 반영 
- 게시글 작성 예상금액 형식 변경
=> ✨feat : 게시글 작성 예상금액 형식 변경

src/components/detail/Detail.jsx, src/components/detail/DetailApplicationList.jsx, src/components/register/SignupPiece.jsx
상세페이지 기타 수정
- 상세페이지 기타 수정
close
=> 🐛fix: 상세페이지 기타 수정

src/components/elements/InputBasic.jsx, src/components/header/Alarm.jsx, src/components/header/UserModal.jsx, src/components/main/PostingCard.jsx, src/components/posting/Posting.jsx, src/redux/modules/alarm/alarmSlice.js, src/shared/layout/Header.jsx
유저 피드백 반영 수정 작업
- 헤더 탭바 모달창 버튼 순서 변경
- 알림 전체 삭제 기능 추가
- 메인 공구  카드 CSS 추가
- 아이폰 미니 기준 모바일 높이 fix
=> ✨유저 피드백 반영 수정 작업

src/components/profile/EmptyContents.jsx, src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/components/profile/ProfileStar.jsx
프로필 빈 컨텐츠인 경우 안내 문구 처리
- 프로필 빈 컨텐츠인 경우 안내 문구 처리
=> ✨feat : 프로필 빈 컨텐츠인 경우 안내 문구 처리

src/components/detail/Detail.jsx, src/components/detail/application/DetailApplicationBtns.jsx
상세페이지 완료 대기 버튼 추가 외
- 완료 대기 게시물 버튼 추가
- 이미지 속성 변경
close
=> ✨feat: 상세페이지 완료 대기 버튼 추가 외

src/components/chat/ChatZone.jsx
채팅 말풍선 패딩 조절
- 채팅 말풍선 패딩 조절
close
=> ♻️feat: 채팅 말풍선 패딩 조절

src/components/header/Alarm.jsx, src/components/header/HeaderPc.jsx, src/redux/modules/alarm/alarmSlice.js, src/shared/layout/Header.jsx
알림 삭제 기능 및 모달 ref 사용
- 알림 삭제 기능 및 모달 ref 사용
=> ♻️refactor : 알림 삭제 기능 및 모달 ref 사용

src/components/header/guideModal/GuideModal.jsx
=> ✨feat : 유저 가이드 로컬 저장

src/components/chat/ChatBody.jsx, src/components/chat/ChatList.jsx, src/components/chat/ChatZone.jsx, src/components/chat/Chatroom.jsx
=> 🐛fix: 채팅 시간 기록

src/components/chat/ChatBody.jsx, src/components/chat/ChatList.jsx, src/components/chat/ChatZone.jsx, src/components/chat/Chatroom.jsx
채팅 스크롤 하단 고정 추가, 중복 구독 해결
- useEffect clean-up 사용, 중복 구독 해결
- 채팅방 입장 시 스크롤 하단 고정
close
=> 🐛fix: 채팅 스크롤 하단 고정 추가, 중복 구독 해결

src/components/header/Alarm.jsx, src/components/header/HeaderMobile.jsx, src/components/header/HeaderPc.jsx, src/components/header/guideModal/GuideModal.jsx, src/components/login/SignIn.jsx, src/components/login/outh/Oauth2RedirectHandler.jsx, src/components/main/EmptyCard.jsx, src/components/main/Map.jsx, src/components/main/PostingCard.jsx, src/components/main/PostingList.jsx, src/components/posting/Posting.jsx, src/components/profile/MyCreation.jsx, src/components/profile/MyParicipation.jsx, src/components/profile/MyProfile.jsx, src/components/profile/Profile.jsx, src/components/profile/ProfileInfo.jsx, src/components/profile/modal/EditProfileModal.jsx, src/core/axios.js, src/redux/config/configStore.js, src/redux/modules/alarm/alarmSlice.js, src/redux/modules/login/signinSlice.js, src/redux/modules/profile/profileSlice.js, src/redux/modules/profile/reviewsSlice.js, src/shared/GlobalStyles.js, src/shared/Router.js, src/shared/layout/Header.jsx, src/utils/option.js
- [] Feature
프로젝트 최종 정리
- 주석 정리 및 안쓰는 코드 제거
=> 🐛 Fix : 프로젝트 최종 정리

src/components/register/signupContents.js
인증번호 제한시간 변경에 따른 placeholder 수정
- 인증번호 제한시간 변경에 따른 placeholder 수정
close
=> ♻️refactor: 인증번호 제한시간 변경에 따른 placeholder 수정
